source 'https://rubygems.org'

gem 'sinatra'
gem 'sinatra-websocket'
gem 'sinatra-sequel'
gem 'sinatra-contrib'
gem 'sinatra-logger'
gem 'pry'
gem 'pry-debugger'
gem 'thin'
gem 'serialport'
gem 'multi_json'
gem 'haml'
gem 'sass'
gem 'sequel'
gem 'sqlite3'
