source 'https://rubygems.org'

gem 'sinatra'
gem 'sinatra-websocket'
gem 'sinatra-sequel'
gem 'sinatra-contrib'
gem 'thin'
gem 'serialport'
gem 'json'
gem 'haml'
gem 'sass'
gem 'sequel'
gem 'sqlite3'
